apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-business-logic-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-business-logic-job
  template:
    metadata:
      labels:
        app: flink-business-logic-job
    spec:
      containers:
        - name: flink-business-logic-job-container
          image: 376163012258.dkr.ecr.us-east-1.amazonaws.com/flink-business-logic-app:latest
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: flink-business-logic-job-service
spec:
  selector:
    app: flink-business-logic-job
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer